# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LangCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StringKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_key', models.CharField(max_length=50, unique=True)),
                ('app_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stringtranslate.AppSet')),
            ],
        ),
        migrations.CreateModel(
            name='StringTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('lang_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stringtranslate.LangCode')),
                ('string_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stringtranslate.StringKey')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stringtable',
            unique_together=set([('string_key', 'lang_code')]),
        ),
    ]
